get_currentuserinfo is deprecated
if WP_DEBUG=true
an error occurs:

ErrorException: Function get_currentuserinfo is deprecated since version 4.5.0! Use wp_get_current_user() instead. in C:\home\htdocs.wordpress\wp-includes\functions.php:5383

tri-catch is not used for backwards compatibility.